### PR TITLE
allow the 2.12 prerelease sdks and prep for release

### PR DESCRIPTION
**Pull request by jakemac53**
* Also removes git overrides in favor of real deps since they exist now

### CODE REVIEW

**Comment by jakemac53** [comment]
This should not be published until https://dart-review.googlesource.com/c/sdk/+/168982 rolls internally

**Comment by jakemac53** [comment]
This has passed the internal presubmits so it is safe to go ahead and land and publish as soon as you get a chance @lrhn

**Comment by lrhn** [comment]
Not sure I want to publish pre-releases. Will wait for Dart 2.12 to be released.

**Comment by jakemac53** [comment]
Yes this has to be published because it is depended on by flutter

**Pull request merged**
